services:
  # Base de datos MySQL
  - type: private-service
    name: rently-mysql
    env: docker
    dockerImage: mysql:8.0
    plan: free  # ðŸ‘ˆ cambia "starter" por "free"
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 0108lomejor
      - key: MYSQL_DATABASE
        value: rently
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1  # mÃ¡ximo permitido gratis

  # Backend Spring Boot
  - type: web
    name: rently-back
    env: docker
    dockerfilePath: ./Rently/Dockerfile
    plan: free  # ðŸ‘ˆ cambia a "free"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://rently-mysql:3306/rently
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: 0108lomejor

  # Frontend Angular + Nginx
  - type: web
    name: rently-front
    env: docker
    dockerfilePath: ./RentlyFront/inicio/Dockerfile
    plan: free  # ðŸ‘ˆ cambia a "free"
