services:
  # 1) Backend Spring
  - type: web
    name: rently-back
    env: docker
    dockerfilePath: ./Rently/Dockerfile
    plan: starter
    envVars:
      - key: SPRING_DATASOURCE_URL
        # esto lo cambias cuando Render cree la DB
        value: jdbc:mysql://YOUR_RENDER_DB_HOST:3306/rently
      - key: SPRING_DATASOURCE_USERNAME
        value: YOUR_DB_USER
      - key: SPRING_DATASOURCE_PASSWORD
        value: YOUR_DB_PASSWORD

  # 2) Frontend Angular + nginx
  - type: web
    name: rently-front
    env: docker
    dockerfilePath: ./RentlyFront/inicio/Dockerfile
    plan: starter

databases:
  - name: rently-db
    databaseName: rently
    plan: free
